#pragma once

#include "ui_mainwindow.h" // Auto-generated by uic
#include <QMainWindow>

namespace HedgeEdit::UI
{
	class MainWindow : public QMainWindow, public Ui_MainWindow
	{
		Q_OBJECT

	public:
		explicit MainWindow(QWidget* parent = nullptr);
		~MainWindow();

	public slots:
		void PropertiesClosed();
		void DebugEnableDarkTheme();
		// TODO
	};

	extern MainWindow* MainInstance;
}
