#pragma once

#include "ui_propertiespanel.h" // Auto-generated by uic
#include <QWidget>

namespace HedgeEdit::UI
{
    class PropertiesPanel : public QWidget, public Ui_PropertiesPanel
    {
        Q_OBJECT

    public:
        explicit PropertiesPanel(QWidget* parent = nullptr);

    protected:
        QSize sizeHint() const override;
        void closeEvent(QCloseEvent* e) override;
    };
}
