/* Define empty macros for any auto-generators that aren't used. */
#ifndef HR_IN_DXGI_FORMAT_AUTOGEN
#define HR_IN_DXGI_FORMAT_AUTOGEN(hlFormat, dxgiFormat1D,\
    dxgiFormat2D, dxgiFormat3D, dxgiFormat4D)
#endif

#ifndef HR_IN_DXGI_FORMAT_AUTOGEN_DEFAULT
#define HR_IN_DXGI_FORMAT_AUTOGEN_DEFAULT()
#endif

HR_IN_DXGI_FORMAT_AUTOGEN(HL_VERTEX_ELEM_FORMAT_FLOAT,
    DXGI_FORMAT_R32_FLOAT, DXGI_FORMAT_R32G32_FLOAT,
    DXGI_FORMAT_R32G32B32_FLOAT, DXGI_FORMAT_R32G32B32A32_FLOAT)

HR_IN_DXGI_FORMAT_AUTOGEN(HL_VERTEX_ELEM_FORMAT_INDEX,
    DXGI_FORMAT_R32_UINT, DXGI_FORMAT_R32G32_UINT,
    DXGI_FORMAT_R32G32B32_UINT, DXGI_FORMAT_R32G32B32A32_UINT)

HR_IN_DXGI_FORMAT_AUTOGEN(HL_VERTEX_ELEM_FORMAT_HALF,
    DXGI_FORMAT_R16_FLOAT, DXGI_FORMAT_R16G16_FLOAT,
    HR_IN_DXGI_FORMAT_AUTOGEN_DEFAULT(), DXGI_FORMAT_R16G16B16A16_FLOAT)

HR_IN_DXGI_FORMAT_AUTOGEN(HL_VERTEX_ELEM_FORMAT_SBYTE,
    DXGI_FORMAT_R8_SINT, DXGI_FORMAT_R8G8_SINT,
    HR_IN_DXGI_FORMAT_AUTOGEN_DEFAULT(), DXGI_FORMAT_R8G8B8A8_SINT)

HR_IN_DXGI_FORMAT_AUTOGEN(HL_VERTEX_ELEM_FORMAT_BYTE,
    DXGI_FORMAT_R8_UINT, DXGI_FORMAT_R8G8_UINT,
    HR_IN_DXGI_FORMAT_AUTOGEN_DEFAULT(), DXGI_FORMAT_R8G8B8A8_UINT)

HR_IN_DXGI_FORMAT_AUTOGEN(HL_VERTEX_ELEM_FORMAT_SBYTE_NORM,
    DXGI_FORMAT_R8_SNORM, DXGI_FORMAT_R8G8_SNORM,
    HR_IN_DXGI_FORMAT_AUTOGEN_DEFAULT(), DXGI_FORMAT_R8G8B8A8_SNORM)

HR_IN_DXGI_FORMAT_AUTOGEN(HL_VERTEX_ELEM_FORMAT_BYTE_NORM,
    DXGI_FORMAT_R8_UNORM, DXGI_FORMAT_R8G8_UNORM,
    HR_IN_DXGI_FORMAT_AUTOGEN_DEFAULT(), DXGI_FORMAT_R8G8B8A8_UNORM)

HR_IN_DXGI_FORMAT_AUTOGEN(HL_VERTEX_ELEM_FORMAT_SHORT,
    DXGI_FORMAT_R16_SINT, DXGI_FORMAT_R16G16_SINT,
    HR_IN_DXGI_FORMAT_AUTOGEN_DEFAULT(), DXGI_FORMAT_R16G16B16A16_SINT)

HR_IN_DXGI_FORMAT_AUTOGEN(HL_VERTEX_ELEM_FORMAT_USHORT,
    DXGI_FORMAT_R16_UINT, DXGI_FORMAT_R16G16_UINT,
    HR_IN_DXGI_FORMAT_AUTOGEN_DEFAULT(), DXGI_FORMAT_R16G16B16A16_UINT)

HR_IN_DXGI_FORMAT_AUTOGEN(HL_VERTEX_ELEM_FORMAT_SHORT_NORM,
    DXGI_FORMAT_R16_SNORM, DXGI_FORMAT_R16G16_SNORM,
    HR_IN_DXGI_FORMAT_AUTOGEN_DEFAULT(), DXGI_FORMAT_R16G16B16A16_SNORM)

HR_IN_DXGI_FORMAT_AUTOGEN(HL_VERTEX_ELEM_FORMAT_USHORT_NORM,
    DXGI_FORMAT_R16_UNORM, DXGI_FORMAT_R16G16_UNORM,
    HR_IN_DXGI_FORMAT_AUTOGEN_DEFAULT(), DXGI_FORMAT_R16G16B16A16_UNORM)

HR_IN_DXGI_FORMAT_AUTOGEN(HL_VERTEX_ELEM_FORMAT_INT,
    DXGI_FORMAT_R32_SINT, DXGI_FORMAT_R32G32_SINT,
    DXGI_FORMAT_R32G32B32_SINT, DXGI_FORMAT_R32G32B32A32_SINT)

HR_IN_DXGI_FORMAT_AUTOGEN(HL_VERTEX_ELEM_FORMAT_UINT,
    DXGI_FORMAT_R32_UINT, DXGI_FORMAT_R32G32_UINT,
    DXGI_FORMAT_R32G32B32_UINT, DXGI_FORMAT_R32G32B32A32_UINT)

/*HR_IN_DXGI_FORMAT_AUTOGEN(HL_VERTEX_ELEM_FORMAT_INT_NORM,
    HR_IN_DXGI_FORMAT_AUTOGEN_DEFAULT(), HR_IN_DXGI_FORMAT_AUTOGEN_DEFAULT(),
    HR_IN_DXGI_FORMAT_AUTOGEN_DEFAULT(), HR_IN_DXGI_FORMAT_AUTOGEN_DEFAULT())

HR_IN_DXGI_FORMAT_AUTOGEN(HL_VERTEX_ELEM_FORMAT_UINT_NORM,
    HR_IN_DXGI_FORMAT_AUTOGEN_DEFAULT(), HR_IN_DXGI_FORMAT_AUTOGEN_DEFAULT(),
    HR_IN_DXGI_FORMAT_AUTOGEN_DEFAULT(), HR_IN_DXGI_FORMAT_AUTOGEN_DEFAULT())*/

/* Undefine all auto-generator macros. */
#undef HR_IN_DXGI_FORMAT_AUTOGEN
