/* Define empty macros for any auto-generators that aren't used. */
#ifndef HL_IN_NN_MOTION_TYPE_AUTOGEN
#define HL_IN_NN_MOTION_TYPE_AUTOGEN(nnMotType, nnMotTypeSuffix, hlMotType)
#endif

#ifndef HL_IN_NN_SUBMOTION_NODE_AUTOGEN
#define HL_IN_NN_SUBMOTION_NODE_AUTOGEN(nnSubMotFormat, nnSuffix, hlSuffix, hlFormat)
#endif

#ifndef HL_IN_NN_SUBMOTION_NODE_ROT_AUTOGEN
#define HL_IN_NN_SUBMOTION_NODE_ROT_AUTOGEN(nnSubMotFormat, nnSubMotTypeSuffix)
#endif

#ifndef HL_IN_NN_SUBMOTION_NODE_IP_AUTOGEN
#define HL_IN_NN_SUBMOTION_NODE_IP_AUTOGEN(nnSubMotFormat, nnSubMotTypeSuffix, hlSubMotTypeSuffix)
#endif

/* NN Motion types. */
HL_IN_NN_MOTION_TYPE_AUTOGEN(HL_NN_MOTIONTYPE_NODE, Node, HL_ANIM_TYPE_BONE)
HL_IN_NN_MOTION_TYPE_AUTOGEN(HL_NN_MOTIONTYPE_CAMERA, Camera, HL_ANIM_TYPE_CAMERA)
HL_IN_NN_MOTION_TYPE_AUTOGEN(HL_NN_MOTIONTYPE_LIGHT, Light, HL_ANIM_TYPE_LIGHT)
HL_IN_NN_MOTION_TYPE_AUTOGEN(HL_NN_MOTIONTYPE_MORPH, Morph, HL_ANIM_TYPE_MORPH)
HL_IN_NN_MOTION_TYPE_AUTOGEN(HL_NN_MOTIONTYPE_MATERIAL, Material, HL_ANIM_TYPE_MATERIAL)

/* NN Submotion Node types. */
HL_IN_NN_SUBMOTION_NODE_AUTOGEN(HL_NN_SMOTTYPE_TRANSLATION_X, Float, Float,
    HL_ANIM_KEY_FORMAT_FLOAT | HL_ANIM_KEY_BONE_TYPE_POS_X)

HL_IN_NN_SUBMOTION_NODE_AUTOGEN(HL_NN_SMOTTYPE_TRANSLATION_Y, Float, Float,
    HL_ANIM_KEY_FORMAT_FLOAT | HL_ANIM_KEY_BONE_TYPE_POS_Y)

HL_IN_NN_SUBMOTION_NODE_AUTOGEN(HL_NN_SMOTTYPE_TRANSLATION_Z, Float, Float,
    HL_ANIM_KEY_FORMAT_FLOAT | HL_ANIM_KEY_BONE_TYPE_POS_Z)

HL_IN_NN_SUBMOTION_NODE_AUTOGEN(HL_NN_SMOTTYPE_TRANSLATION_XYZ, Vector, Float3,
    HL_ANIM_KEY_FORMAT_FLOAT | HL_ANIM_KEY_DIMENSION_3D | HL_ANIM_KEY_BONE_TYPE_POS_XYZ)

HL_IN_NN_SUBMOTION_NODE_AUTOGEN(HL_NN_SMOTTYPE_SCALING_X, Float, Float,
    HL_ANIM_KEY_FORMAT_FLOAT | HL_ANIM_KEY_BONE_TYPE_SCALE_X)

HL_IN_NN_SUBMOTION_NODE_AUTOGEN(HL_NN_SMOTTYPE_SCALING_Y, Float, Float,
    HL_ANIM_KEY_FORMAT_FLOAT | HL_ANIM_KEY_BONE_TYPE_SCALE_Y)

HL_IN_NN_SUBMOTION_NODE_AUTOGEN(HL_NN_SMOTTYPE_SCALING_Z, Float, Float,
    HL_ANIM_KEY_FORMAT_FLOAT | HL_ANIM_KEY_BONE_TYPE_SCALE_Z)

HL_IN_NN_SUBMOTION_NODE_AUTOGEN(HL_NN_SMOTTYPE_SCALING_XYZ, Vector, Float3,
    HL_ANIM_KEY_FORMAT_FLOAT | HL_ANIM_KEY_DIMENSION_3D | HL_ANIM_KEY_BONE_TYPE_SCALE_XYZ)

HL_IN_NN_SUBMOTION_NODE_AUTOGEN(HL_NN_SMOTTYPE_USER_UINT32, UInt, UInt,
    HL_ANIM_KEY_FORMAT_UINT | HL_ANIM_KEY_TYPE_CUSTOM)

HL_IN_NN_SUBMOTION_NODE_AUTOGEN(HL_NN_SMOTTYPE_USER_FLOAT, Float, Float,
    HL_ANIM_KEY_FORMAT_FLOAT | HL_ANIM_KEY_TYPE_CUSTOM)

/* TODO: HL_NN_SMOTTYPE_NODEHIDE */

/* NN Submotion Node rotation types. */
HL_IN_NN_SUBMOTION_NODE_ROT_AUTOGEN(HL_NN_SMOTTYPE_ROTATION_X, Float)
HL_IN_NN_SUBMOTION_NODE_ROT_AUTOGEN(HL_NN_SMOTTYPE_ROTATION_Y, Float)
HL_IN_NN_SUBMOTION_NODE_ROT_AUTOGEN(HL_NN_SMOTTYPE_ROTATION_Z, Float)

/* TODO: HL_NN_SMOTTYPE_QUATERNION */

/* NN Submotion Node bezier types. */
HL_IN_NN_SUBMOTION_NODE_IP_AUTOGEN(HL_NN_SMOTTYPE_TRANSLATION_X, Bezier, FloatIP)
HL_IN_NN_SUBMOTION_NODE_IP_AUTOGEN(HL_NN_SMOTTYPE_TRANSLATION_Y, Bezier, FloatIP)
HL_IN_NN_SUBMOTION_NODE_IP_AUTOGEN(HL_NN_SMOTTYPE_TRANSLATION_Z, Bezier, FloatIP)

HL_IN_NN_SUBMOTION_NODE_IP_AUTOGEN(HL_NN_SMOTTYPE_SCALING_X, Bezier, FloatIP)
HL_IN_NN_SUBMOTION_NODE_IP_AUTOGEN(HL_NN_SMOTTYPE_SCALING_Y, Bezier, FloatIP)
HL_IN_NN_SUBMOTION_NODE_IP_AUTOGEN(HL_NN_SMOTTYPE_SCALING_Z, Bezier, FloatIP)
HL_IN_NN_SUBMOTION_NODE_IP_AUTOGEN(HL_NN_SMOTTYPE_USER_FLOAT, Bezier, FloatIP)

/* Undefine all auto-generator macros. */
#undef HL_IN_NN_MOTION_TYPE_AUTOGEN
#undef HL_IN_NN_SUBMOTION_NODE_AUTOGEN
#undef HL_IN_NN_SUBMOTION_NODE_ROT_AUTOGEN
#undef HL_IN_NN_SUBMOTION_NODE_IP_AUTOGEN
